const mongoose = require('mongoose');

const financialRecordSchema = new mongoose.Schema(
    {
        tenantId: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
            ref: 'User',
            index: true, // Crucial for multi-tenant query performance
        },
        periodDate: {
            // E.g., '2026-02-01'. Represents the financial month.
            type: Date,
            required: true,
        },
        // --- CORE FINANCIAL METRICS ---
        // ALL STORED IN INTEGER CENTS to prevent floating point compounding errors 
        // Example: $10,500.50 is stored as 1050050
        revenueCents: {
            type: Number,
            required: true,
            default: 0,
        },
        cogsCents: {
            type: Number, // Cost of Goods Sold
            required: true,
            default: 0,
        },
        opexCents: {
            type: Number, // Operating Expenses
            required: true,
            default: 0,
        },
        cashOnHandCents: {
            type: Number, // Total liquid cash at the end of the period
            required: true,
            default: 0,
        },
        liabilitiesCents: {
            type: Number, // Total short-term debt / immediate liabilities
            required: true,
            default: 0,
        },
        // --- PRECOMPUTED ENGINE METRICS ---
        // These are generated by the Risk Engine, not the user
        calculatedMetrics: {
            runwayMonths: { type: Number },
            riskScore: { type: Number }, // 0 to 100
            collapseProbability: { type: Number }, // Percentage
        },
        // --- FORWARD PROJECTIONS ---
        // Generated by Forecast Engine
        forecasts: [
            {
                monthIndex: { type: Number },
                projectedCashBaseCents: { type: Number },
                projectedCashBestCents: { type: Number },
                projectedCashWorstCents: { type: Number },
                // New Detailed Metrics
                projectedRevenueCents: { type: Number },
                projectedExpensesCents: { type: Number },
                projectedNetIncomeCents: { type: Number },
                projectedRiskScore: { type: Number }
            }
        ]
    },
    {
        timestamps: true,
    }
);

// COMPOUND INDEX: A single tenant (startup) can only have ONE financial record per specific month.
financialRecordSchema.index({ tenantId: 1, periodDate: 1 }, { unique: true });

const FinancialRecord = mongoose.model('FinancialRecord', financialRecordSchema);

module.exports = FinancialRecord;
